### ISSUE TITLE
WGDEC-2021 QCrec: The reported depth (DepthUpper, DepthLower, DepthShoot, DepthHaul) is shallower than 190 m?

### ISSUE THREAD

**Issue by Osanna123** [ices-eg/wg_WGDEC#36]
“The ICES VME Database is typically for deep-water VME indicator/habitat records found in water depths generally 200 m or deeper.  Shallow water records shall not be included within the VME Database without strong justification. Please contact the ICES Data Centre prior to resubmitting this record”

**Comment by Osanna123** [comment]
This would need a follow-up from the WGDEC QC sub-group

**Comment by david9317** [comment]
I agree that this need to be discussed with the DEC QC group and possibly with the general DEC group. There has been discussion around making the database more taxa specific rather than depth specific as some taxa are not restricted by depth and placing this limit on submissions introduces an artificial bias in the database for such species that will impact its use for constructing distribution models. This would be a big change that would need to be discussed and agreed by the larger group.

**Comment by Osanna123** [comment]
present check works only for DepthLower >190m: 
https://datsu.ices.dk/web/chkDetails.aspx?DatasetID=127&RecordID=77&groupFilterID=1720
