### ISSUE TITLE
Format changes

### ISSUE THREAD

**Issue by cmspinto** [ices-eg/wg_WGDEC#57]
Compared and contrasted the 2021 & 2022 data calls .
The differences are summarised in the table below where: ‘-‘ means no difference, and where there are differences the bold options are what we want for the 2023 data call.

| Table | 2021 | 2022 |
| ------------- | ------------- | ------------- |
|File info | - | -|
|VME cruise | - | -|
|VME sample | Depths (upper, lower, shoot   & haul) optional | Depths (upper, lower, shoot   & haul) conditional|
|VME data* | GeneralTaxonDesc – optional | GeneralTaxonDesc – conditional|
|Has: Number,   Weight, Density, %cover and SACFOR | Has: VMEQuantMeth1, VMEQValue1, VMEQMeth2, VMEQValue2.|

* the 2021 fields (Number, weight etc.) were removed and replaced with VMEQuantMethod1 etc. We want (need) to roll back to the 2021 version for these. For the other differences, we’ll stick with the 2022 version.

**Comment by david9317** [comment]
Thanks both. So, I've had a read at the 2021 DEC report (section 3.3) where quantitative information on VMEs is discussed and I copy and paste the relevant section below for your convenience:

•	Quantitative information on VME indicators – It was agreed that encouraging the sub-mission of more quantitative information on VME indicator occurrence was an im-portant step to ensuring the VME database was more “futureproof” and would contain the data needed for future VME weighting and predictive habitat modelling require-ments.  Therefore, a revision was made to how quantitative information on VME indi-cators should be submitted. Data providers will now be required to actively decide whether they are submitting presence data, rather than this being the default option.  The obligation for these fields would also be changed from Optional to Mandatory for the first quantification method option and Conditional for the second quantitative method option.

Now, my take on this is that presence data has been submitted to the data base by default before these changes were made, which seems uncontroversial. And the motivation behind losing the 5 previous quantification fields (Number, Weight, Density, %Cover and SACFOR) and replacing them with the new fields (VMEQuantMethod1&2 and VMEQuantValue1&2) was to: "encourage the submission of more quantitative data" & "futureproof the database". 

While I agree with this motivation, the fact remains that the new fields (VMEQuantMethod1&2 and VMEQuantValue1&2) make derivation of the VME index (weighted algorithm) impossible, and any newly submitted data in this format does not map onto the existing database structure. Like I said earlier, these were unforeseen consequences in making this change. 

I suggest that in order to maintain compatibility with the existing database and so that the VME index can be derived, we change it back to the way it was in the 2021 data call with the 5 previously listed quantification methods specified as separate fields. There will be no need to have a separate 'Presence' column. At some point in the future, when the work on changes to the VME index are complete, we could then revisit this issue collaboratively with the data centre and see if there are any changes that could be made to encourage more quantitative data submission.

Does that make sense? Am I missing something?
